### ISSUE TITLE
Reemplazar foto placeholder del landing con una del equipo

### ISSUE THREAD

**Issue by rdiazv** [5rabbits/site#6]
Puede ser una foto o tal vez un mosaico en base a las fotos individuales.

**Comment by a-bx** [comment]
igual es más fácil mantener la foto de cada uno que una foto de un equipo completo actualizada, de hecho todas las que tenemos están des-actualizadas (falta gente, sobra gente)

**Comment by rdiazv** [comment]
👍 tiene razón.

**Comment by rdiazv** [comment]
Se agregó un mosaico.
